[tool.poetry]
name = "caldata-dsa-dwr"
version = "0.1.0"
description = "CalData's DSA project with DWR"
authors = ["Monica Bobra <monica.bobra@innovation.ca.gov>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.10"
scikit-learn = "^1.6.0"
pandas = "^2.2.3"
numpy = "^2.2.0"
matplotlib = "^3.10.0"
jupyterlab = "^4.3.3"
shiny = "^1.2"
shinyswatch = "^0.8"
shinywidgets = "^0.5"
plotly = "5.24"
dateparser = "^1.2"
openpyxl = "^3.1"
seaborn = "^0.13.2"

[tool.poetry.group.hostdev]
optional = true

[tool.poetry.group.hostdev.dependencies]
rsconnect-python = "^1.25"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
