[tool.poetry]
name = "caldata-dsa-dwr"
version = "0.1.0"
description = "CalData's DSA project with DWR"
authors = ["Monica Bobra <monica.bobra@innovation.ca.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
scikit-learn = "^1.6.0"
pandas = "^2.2.3"
numpy = "1.26.4"
matplotlib = "^3.10.0"
jupyterlab = "^4.3.3"
vtools3 = "^3.7.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
