name: Build and deploy Python app to staging

on:
  push:
    branches:
      - presistent-state
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python version
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !.venv/

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Staging Slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'caldata-dsa-dwr-odi'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_STAGING }}